#!/bin/bash
# Sets up a go installation for the Travis CI environment.

set -e

export GOPATH=$HOME
export PATH=$PATH:$HOME/go/bin:$GOPATH/bin
export repo_dir=$PWD
export github_repo=$(basename $PWD)
export github_user=$(basename $(cd .. && pwd))
export gopath_user=$GOPATH/src/github.com/$github_user
export gopath_repo=$gopath_user/$github_repo

hg clone -r go1 https://code.google.com/p/go $HOME/go
cd $HOME/go/src && ./make.bash
cd $HOME
mkdir -p $gopath_user || true
mkdir -p $GOPATH/bin || true
mkdir -p $GOPATH/pkg || true
mv $repo_dir $gopath_repo
go test github.com/$gihub_user/$gihub_repo/... -v
