#!/bin/bash
# Sets up a go installation for the Travis CI environment.

export GOPATH=$HOME
export PATH=$PATH:$HOME/go/bin:$GOPATH/bin
export go_release=go1
export repo_dir=$PWD
export github_repo=$(basename $PWD)
export github_user=$(basename $(cd .. && pwd))
export gopath_user=$GOPATH/src/github.com/$github_user
export gopath_repo=$gopath_user/$github_repo

echo -n Fetching go sources...
OUT=/tmp/go.fetch.$PPID
hg clone -r $go_release https://code.google.com/p/go $HOME/go 1>$OUT 2>&1
if [ $? -ne 0 ]; then
  echo FAILED
  cat $OUT
  exit 1
fi
rm $OUT
echo " done."

echo -n Compiling go...
OUT=/tmp/go.compile.$PPID
cd $HOME/go/src && ./make.bash 1>$OUT 2>&1
if [ $? -ne 0 ]; then
  echo FAILED
  cat $OUT
  exit 1
fi
rm $OUT
echo " done."

set -e
cd $HOME
mkdir -p $gopath_user || true
mkdir -p $GOPATH/bin || true
mkdir -p $GOPATH/pkg || true
mv $repo_dir $gopath_repo

go get -v github.com/$gihub_user/$gihub_repo/...
go test -v github.com/$gihub_user/$gihub_repo/...
