#!/bin/bash

set -e
REPO_DIR=$PWD
GITHUB_REPO=$(basename $PWD)
GITHUB_USER=$(basename $(cd .. && pwd))
RELEASE_URL=http://go.googlecode.com/files/go1.0.2.linux-386.tar.gz
LOCAL_GO=/usr/local/go
RUNNING_USER=$USER

export PATH=$PATH:$LOCAL_GO/bin

sudo mkdir $LOCAL_GO
sudo chown $RUNNING_USER $LOCAL_GO
echo Installing Go
curl --silent $RELEASE_URL | tar -C /usr/local -xzf -
mkdir -p $LOCAL_GO/src/pkg/github.com/$GITHUB_USER
cp -r $REPO_DIR $LOCAL_GO/src/pkg/github.com/$GITHUB_USER/$GITHUB_REPO
echo Fetching packaage dependicies
go get -v github.com/$GITHUB_USER/$GITHUB_REPO/...
echo Fetching test dependicies
TEST_DEPS=$(go list -f '{{.TestImports}}' github.com/$GITHUB_USER/$GITHUB_REPO/... | sed -e 's/^\[//' | sed -e 's/\]$//')
if [ "$TEST_DEPS" ]; then
  go get -v $TEST_DEPS
fi
go test -v github.com/$GITHUB_USER/$GITHUB_REPO/...
